#!/usr/bin/env python3
import argparse
import subprocess
import threading
import re
import json
import sys
import os
import time

# --- Configuration & State ---
WEBRTC_ADDR = None
ADDR_LOCK = threading.Lock()

class Colors:
    RESET = "\033[0m"
    POLKADOT = "\033[35m"  # Magenta
    TS_GEN = "\033[36m"    # Cyan
    SUCCESS = "\033[32m"   # Green
    WARN = "\033[33m"      # Yellow

def print_log(source, message, color):
    timestamp = time.strftime("%H:%M:%S")
    sys.stdout.write(f"{color}[{timestamp}] [{source}] {message}{Colors.RESET}\n")
    sys.stdout.flush()

def generate_ts_file(address):
    """Generates the TypeScript file with the injected bootnode"""
    try:
        with open(ARGS.chain_spec, 'r') as f:
            spec_data = json.load(f)
    except Exception as e:
        print_log("TS_Gen", f"Error reading chain spec: {e}", Colors.WARN)
        return

    # Inject the captured WebRTC address
    # We use a list with ONLY our local node to ensure connection
    spec_data['bootNodes'] = [address]

    # We use the full raw spec for local dev to avoid genesis mismatches
    json_str = json.dumps(spec_data)

    # Create the TypeScript content
    ts_content = f"// Auto-generated by orchestrator.py\nexport const chainSpec = JSON.stringify({json_str});"

    try:
        with open(ARGS.ts_output, 'w') as f:
            f.write(ts_content)
        print_log("TS_Gen", f"Updated {ARGS.ts_output} with new bootnode!", Colors.SUCCESS)
    except Exception as e:
        print_log("TS_Gen", f"Error writing TS file: {e}", Colors.WARN)

def run_polkadot():
    global WEBRTC_ADDR

    cmd = [
        ARGS.polkadot_bin,
        "--dev",
        "-lsub-libp2p=debug",
        "-llitep2p=debug",
        "-lsub-libp2p::peerset=trace",
        "-lsub-libp2p::behaviour=debug",
        f"--listen-addr=/ip4/{ARGS.ip}/tcp/30333",
        f"--listen-addr=/ip4/{ARGS.ip}/udp/30334/webrtc-direct",
        "--sync=full",
        "--rpc-cors=all",
        "--unsafe-rpc-external",
        "--rpc-max-response-size=26214400" # 25MB to fit chainspec
    ]

    print_log("System", f"Starting Polkadot...", Colors.SUCCESS)

    try:
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1
        )
    except FileNotFoundError:
        print_log("System", f"Error: Binary {ARGS.polkadot_bin} not found.", Colors.WARN)
        os._exit(1)

    # Robust Regex for WebRTC address
    addr_pattern = re.compile(r"listening on:\s+(/.*(?:webrtc|webrtc-direct).*certhash.*p2p.*)", re.IGNORECASE)

    while True:
        line = process.stdout.readline()
        if not line and process.poll() is not None:
            break
        if line:
            clean_line = line.strip()
            print_log("Polkadot", clean_line, Colors.POLKADOT)

            match = addr_pattern.search(clean_line)
            if match:
                found_addr = match.group(1).strip()
                with ADDR_LOCK:
                    if WEBRTC_ADDR != found_addr:
                        WEBRTC_ADDR = found_addr
                        print_log("System", f"Captured Address: {WEBRTC_ADDR}", Colors.SUCCESS)
                        # Generate the TS file immediately upon finding address
                        generate_ts_file(WEBRTC_ADDR)

    rc = process.poll()
    print_log("System", f"Polkadot exited with code {rc}", Colors.WARN)
    os._exit(rc)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--ip", default="127.0.0.1")
    parser.add_argument("--polkadot-bin", default="./target/debug/polkadot")
    parser.add_argument("--chain-spec", default="./dev-chain-spec.json")
    # New argument for the output file
    parser.add_argument("--ts-output", required=True, help="Path to write the .ts file (e.g., src/local-chain.ts)")

    ARGS = parser.parse_args()

    if not os.path.exists(ARGS.chain_spec):
        print_log("System", f"Error: Chain spec file '{ARGS.chain_spec}' not found.", Colors.WARN)
        sys.exit(1)

    try:
        run_polkadot()
    except KeyboardInterrupt:
        print_log("System", "Shutting down...", Colors.SUCCESS)
        sys.exit(0)

